### ISSUE TITLE
How to force bitmask/leap to only use tcp, not udp?

### ISSUE THREAD

**Issue by tlaurion** [leapcode/bitmask_client#1011]
When doing a tcpdump for the destination host corresponding to the vpn host, I only see udp traffic attempting to go out for port 443. Most of the time, it is ok, but on some guest network, it would be better to use tcp only and I cnanot find where to set that.

Where would that be?
I have .config/leap/providers/xxx/eip-service.json where i attempted to delete all references to udpbut without success.

Thanks

**Comment by tlaurion** [comment]
duplicate of https://leap.se/code/issues/6816

**Comment by tlaurion** [comment]
Seems like that issue tracking system is not checked?

**Comment by just1602** [comment]
[This should work now](https://github.com/leapcode/bitmask_android/issues/147#issuecomment-234451599)

**Comment by elijh** [comment]
as noted in the other issue, the client does not currently probe the network to try different protocols, but the provider can choose to offer only tcp. because tcp is slower but produces fewer errors, the providers demo.bitmask.net and riseup.net have switched to tcp only. there is another issue on the official bitmask bugtracker at https://leap.se/code to add support for switching protocols

**Comment by tlaurion** [comment]
stil present and commente don: https://github.com/leapcode/bitmask_android/issues/147#issuecomment-234451599
