### ISSUE TITLE
Fail to start Bitmask on Ubuntu 15.10 since the latest upgrade

### ISSUE THREAD

**Issue by bungabunga** [leapcode/bitmask_client#930]
I cant't start Bitmask on Ubuntu 15.10 anymore since updates a day or two ago.

log:
https://gist.github.com/bungabunga/1c3689e16e58c347b721

I also noticed that Bitmask doesn't offer the repository for Ubuntu Wily (15.10) only Vivid (15.04) and that the installation from repository installs Bitmask 0.8.1 not the latest version (0.9).

EDIT:
Reinstall doesn't help, even if I manualy delete config files. But if I install Bitmask as a stand alone app it works.

**Comment by wrapper** [comment]
I get the same except that my last two lines look like this:

  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libssl.so: cannot open shared object file: No such file or directory

**Comment by ivanalejandro0** [comment]
Hi @bungabunga ... the `ImportError: cannot import name signal` error is already fixed, can you try again?
For more information see: https://leap.se/code/issues/7575

@wrapper most likely your issue is a different one, can you report your issue with more details on https://leap.se/code/projects/report-issues ?

**Comment by bungabunga** [comment]
yes, it works now, thank you!
